import { Platform, StyleSheet } from "react-native";
import { BTN_H, BOTTOM_BAR_H, RIBBON_H, ENTITY_PANEL_H } from "@/constants/gameConstants";

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#081828",
    overflow: "hidden",
  },
  board: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  boardElevated: {
    ...Platform.select({
      web: {
        filter: "drop-shadow(0px 12px 32px rgba(0,10,30,0.85))",
      } as any,
      default: {
        elevation: 24,
        shadowColor: "#000A1E",
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.85,
        shadowRadius: 24,
      },
    }),
  },
  entityPanel: {
    position: "absolute",
    left: 0,
    right: 0,
    height: ENTITY_PANEL_H,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    backgroundColor: "rgba(18, 12, 4, 0.97)",
    borderTopWidth: 1,
    borderTopColor: "#6A4A1C",
    zIndex: 18,
  },
  ribbon: {
    position: "absolute",
    left: 0,
    right: 0,
    height: RIBBON_H,
    overflow: "hidden",
    backgroundColor: "rgba(58, 44, 18, 0.98)",
    borderTopWidth: 1,
    borderTopColor: "#8A6A2C",
  },
  ribbonContent: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  ribbonItem: {
    width: 82,
    height: RIBBON_H - 30,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#7A6030",
    backgroundColor: "#3A2C12",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  ribbonItemDisabled: {
    borderColor: "#4A3A1A",
    backgroundColor: "#2A200A",
  },
  ribbonItemArmed: {
    borderColor: "#FFD700",
    backgroundColor: "#2A2008",
  },
  ribbonName: {
    fontSize: 10,
    fontFamily: "Cinzel_400Regular",
    color: "#C8A24A",
  },
  ribbonNameArmed: {
    color: "#FFD700",
  },
  ribbonCost: {
    fontSize: 10,
    fontFamily: "Inter_500Medium",
    color: "#A08C68",
  },
  ribbonCostFree: {
    color: "#44DD88",
    fontFamily: "Cinzel_700Bold",
  },
  ribbonCostBuilt: {
    color: "#E04040",
    fontFamily: "Cinzel_700Bold",
  },
  ribbonDim: {
    color: "#786848",
  },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(54, 40, 14, 0.98)",
    borderTopWidth: 1,
    borderTopColor: "#8A6A2C",
  },
  bottomBarInner: {
    height: BOTTOM_BAR_H,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    gap: 6,
  },
  menuBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#7A6030",
    backgroundColor: "#3A2A10",
  },
  menuBtnText: {
    fontSize: 11,
    fontFamily: "Cinzel_400Regular",
    color: "#A08860",
  },
  buildBtn: {
    height: BTN_H,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#9A7830",
    backgroundColor: "#3A2A10",
  },
  buildBtnActive: {
    backgroundColor: "#C8A24A",
    borderColor: "#C8A24A",
  },
  buildBtnDisabled: {
    borderColor: "#4A3A1A",
    backgroundColor: "#2A1E08",
  },
  buildBtnText: {
    fontSize: 11,
    fontFamily: "Cinzel_400Regular",
    color: "#C8A24A",
  },
  buildBtnTextActive: {
    color: "#0D0A06",
  },
  buildBtnTextDisabled: {
    color: "#5A4A22",
  },
  goldDisplay: {
    height: BTN_H,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    paddingHorizontal: 8,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#7A6030",
    backgroundColor: "#3A2A10",
  },
  goldTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  goldIcon: {
    fontSize: 12,
  },
  goldAmount: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    color: "#C8A24A",
  },
  goldNet: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
  },
  goldNetPos: {
    color: "#70C870",
  },
  goldNetNeg: {
    color: "#E07060",
  },
  lakeModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.72)",
    justifyContent: "center",
    alignItems: "center",
  },
  lakeModalBox: {
    backgroundColor: "#1E1A10",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#4A7FA5",
    padding: 24,
    width: 320,
    alignItems: "center",
  },
  lakeModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#7EC8E3",
    marginBottom: 6,
  },
  lakeModalSubtitle: {
    fontSize: 12,
    color: "#8C9BAB",
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 18,
  },
  lakeModalAmount: {
    fontSize: 44,
    fontWeight: "800",
    color: "#C8D8E8",
    marginBottom: 12,
  },
  lakeSliderRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginBottom: 20,
    gap: 8,
  },
  lakeStepBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#2A3A4A",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#4A7FA5",
  },
  lakeStepText: {
    fontSize: 20,
    color: "#7EC8E3",
    lineHeight: 24,
  },
  lakeTrackHitZone: {
    flex: 1,
    height: 44,
    justifyContent: "center",
  },
  lakeTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#2A3A4A",
    position: "relative",
    overflow: "visible",
  },
  lakeTrackFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#4A7FA5",
    borderRadius: 4,
  },
  lakeThumb: {
    position: "absolute",
    top: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#7EC8E3",
    marginLeft: -12,
    borderWidth: 2,
    borderColor: "#1E1A10",
  },
  lakeModalButtons: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  lakeCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#2A2218",
    borderWidth: 1,
    borderColor: "#5A4A2A",
    alignItems: "center",
  },
  lakeCancelText: {
    color: "#8A7A5A",
    fontWeight: "600",
    fontSize: 15,
  },
  lakeConfirmBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#1A3A5A",
    borderWidth: 1,
    borderColor: "#4A7FA5",
    alignItems: "center",
  },
  lakeConfirmText: {
    color: "#7EC8E3",
    fontWeight: "700",
    fontSize: 15,
  },
  spacer: {
    flex: 1,
  },
  undoBtn: {
    height: BTN_H,
    width: BTN_H,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    gap: 1,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#9A7830",
    backgroundColor: "#3A2A10",
  },
  undoBtnDisabled: {
    borderColor: "#6A5A28",
    backgroundColor: "#2E2208",
  },
  undoBtnLabel: {
    fontSize: 9,
    fontFamily: "Cinzel_400Regular",
    color: "#C8A24A",
    letterSpacing: 0.5,
  },
  undoBtnLabelDisabled: {
    color: "#6A5828",
  },
  undoBtnIcon: {
    fontSize: 17,
    color: "#C8A24A",
  },
  undoBtnIconDisabled: {
    color: "#6A5828",
  },
  endTurnBtn: {
    height: BTN_H,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    paddingHorizontal: 14,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#B08030",
    backgroundColor: "#6A4014",
  },
  endTurnText: {
    fontSize: 11,
    fontFamily: "Cinzel_700Bold",
    color: "#F0D080",
    letterSpacing: 0.5,
  },
  endTurnArrow: {
    fontSize: 13,
    color: "#F0D080",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.65)",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCard: {
    width: 300,
    backgroundColor: "#3A2A10",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#9A7830",
    padding: 28,
    gap: 12,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: "Cinzel_700Bold",
    color: "#F0D080",
    letterSpacing: 0.5,
  },
  modalBody: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "#C8A870",
    textAlign: "center",
    lineHeight: 20,
  },
  modalRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  modalStayBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#7A6030",
    backgroundColor: "#2A1E08",
    alignItems: "center",
  },
  modalStayText: {
    fontSize: 13,
    fontFamily: "Cinzel_400Regular",
    color: "#C8A24A",
  },
  modalLeaveBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#AA3A2A",
    backgroundColor: "#4A1A10",
    alignItems: "center",
  },
  modalLeaveText: {
    fontSize: 13,
    fontFamily: "Cinzel_700Bold",
    color: "#F07060",
  },
  econCard: {
    width: 320,
    backgroundColor: "#3A2A10",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#9A7830",
    padding: 24,
    gap: 8,
  },
  econTitle: {
    fontSize: 16,
    fontFamily: "Cinzel_700Bold",
    color: "#F0D080",
    letterSpacing: 0.5,
    marginBottom: 4,
    textAlign: "center",
  },
  econSection: {
    gap: 4,
  },
  econSectionLabel: {
    fontSize: 10,
    fontFamily: "Cinzel_400Regular",
    color: "#786A54",
    letterSpacing: 1,
    marginBottom: 2,
  },
  econRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  econUpkeepCategoryGap: {
    marginTop: 8,
  },
  econRowLabel: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "#C8A870",
    flex: 1,
  },
  econLabelRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  econPer: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    color: "#786A54",
  },
  econRowValue: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    color: "#7EC87E",
  },
  econEmpty: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: "#786A54",
    fontStyle: "italic",
  },
  econDivider: {
    height: 1,
    backgroundColor: "#6A5020",
    marginVertical: 4,
  },
  econNetLabel: {
    fontSize: 14,
    fontFamily: "Cinzel_400Regular",
    color: "#D0B880",
  },
  econNetValue: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    color: "#C8A24A",
  },
  econCloseBtn: {
    marginTop: 8,
    paddingVertical: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#7A6030",
    backgroundColor: "#2A1E08",
    alignItems: "center",
  },
  econCloseBtnText: {
    fontSize: 13,
    fontFamily: "Cinzel_400Regular",
    color: "#C8A24A",
  },
  aiTurnBtn: {
    backgroundColor: "#1A1A3A",
    borderColor: "#4A4A8A",
  },
  aiTurnText: {
    fontSize: 12,
    fontFamily: "Cinzel_400Regular",
    color: "#8888CC",
    letterSpacing: 0.5,
  },
  devBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#7A6030",
    backgroundColor: "#3A2A10",
  },
  devBtnInactive: {
    borderColor: "#8A2222",
    backgroundColor: "#3A0808",
  },
  devBtnActive: {
    borderColor: "#00FF88",
    backgroundColor: "#003322",
  },
  devBtnText: {
    fontSize: 11,
    fontFamily: "Cinzel_400Regular",
    letterSpacing: 0.5,
  },
  devBtnTextInactive: {
    color: "#CC4444",
  },
  devBtnTextActive: {
    color: "#00FF88",
  },
  prevActionBtn: {
    height: BTN_H,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#00BB66",
    backgroundColor: "#002211",
  },
  nextActionBtn: {
    height: BTN_H,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#00FF88",
    backgroundColor: "#003322",
  },
  nextActionBtnText: {
    fontSize: 11,
    fontFamily: "Cinzel_700Bold",
    color: "#00FF88",
    letterSpacing: 0.5,
  },
  gameResultOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.80)",
    alignItems: "center",
    justifyContent: "center",
  },
  gameResultCard: {
    width: 320,
    backgroundColor: "#1E1608",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#9A7830",
    padding: 36,
    alignItems: "center",
    gap: 16,
  },
  gameResultTitle: {
    fontSize: 28,
    fontFamily: "Cinzel_700Bold",
    letterSpacing: 1,
  },
  gameResultVictoryTitle: {
    color: "#F0D060",
  },
  gameResultDefeatTitle: {
    color: "#E06050",
  },
  gameResultBody: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "#C8A870",
    textAlign: "center",
    lineHeight: 22,
  },
  gameResultBtn: {
    marginTop: 8,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#9A7830",
    backgroundColor: "#3A2A10",
    alignItems: "center",
  },
  gameResultBtnText: {
    fontSize: 14,
    fontFamily: "Cinzel_700Bold",
    color: "#F0D080",
    letterSpacing: 0.5,
  },
  gameResultMenuBtn: {
    backgroundColor: "#2A1E08",
    borderColor: "#6A5020",
  },
  gameResultMenuBtnText: {
    color: "#C8A24A",
    fontSize: 12,
  },
  dominanceContinueBtn: {
    backgroundColor: "#1A3A20",
    borderColor: "#4A8A50",
  },
  dominanceContinueBtnText: {
    color: "#80D090",
  },
  splashOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#0D0A06",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  splashPreloadImg: {
    position: "absolute",
    width: 1,
    height: 1,
    opacity: 0,
  },
  splashTitle: {
    fontFamily: "Cinzel_700Bold",
    fontSize: 34,
    color: "#C8A24A",
    letterSpacing: 2,
    textAlign: "center",
  },
  splashSeparator: {
    width: 180,
    height: 1.5,
    backgroundColor: "#C8A24A",
    marginVertical: 14,
    opacity: 0.7,
  },
  splashSubtitle: {
    fontFamily: "Cinzel_400Regular",
    fontSize: 17,
    color: "#D4BF96",
    letterSpacing: 1,
    textAlign: "center",
  },
});

export default styles;
